### ISSUE TITLE
Modifying a different file

### ISSUE THREAD

**Issue by PStellmann** [schematron-quickfix/sqf#5] opened 2015-06-02 07:13 UTC
Think of the following (simplified) scenario:
In your actual xml file you have "ref" elements that should contain only those values declared in a seperate file that could look like this:

```
<KeyList>
    <Key>Key1</Key>
    <Key>Key2</Key>
</KeyList
```

Now one set of QuickFixes would obviously be to adjust the content of the ref element (preverably as multi-fix). But another QuickFix could be to add a new declaration to the seperate file. So maybe add an optional uri-attribute to the activity elements?

This topic might as we be related to an oxygen problem when dealing with XInclude, which I just discovered and reported here: http://www.oxygenxml.com/forum/topic11575.html

**Comment by nkutsche** [comment] 2015-06-06 10:34
You are right, to support QuickFixes in different files would be a nice feature. But the SQF language does already support this:
The match attribute of the activity elements allows an XPath expression, so it would be allowed also this:

```
<sqf:add match="doc('keylist.xml')/KeyList" position="last-child" target="Key" node-type="element" select="Key2">
```

The problem is, no implementation supports this. But theoretical it is possible.

**Comment by octavianN** [comment] 2015-06-08 09:10
Yes, I think Nico is right, in the match attribute you should be able to specify the document that you want to modify using the doc() function. In this way an operation can be executed in other file than the current one.
We already implemented this in oXygen and it will be available in the next release version.

**Comment by PStellmann** [comment] 2015-06-10 06:28
Great. Will oXygen open the other document(s) so you can undo the changes?

**Comment by octavianN** [comment] 2015-06-10 06:44
When a fix it is applied in other document, the document it is opened in an editor and then performed the fix. It is the same thing as you open the document manually and then apply the fix there. The editor will be marked as modified and you will have undo support.

**Comment by nkutsche** [comment] 2015-06-10 07:00
As usual oxygen do no half-way measures. I close this issue

**Closed as completed by nkutsche** 2015-06-10 07:00 UTC
Labels: enhancement
